import java.awt.Color;
import project.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author BSIT-4D
 */
public class monitoring extends javax.swing.JFrame {

    /**
     * Creates new form monitoring
     */
    public monitoring() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Blogout = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        memberlist1 = new javax.swing.JTable();
        search5 = new javax.swing.JButton();
        MIDv1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        namev1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        numberv1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        genderv1 = new javax.swing.JComboBox<>();
        agev1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        yearv1 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        amountv1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        Activev1 = new javax.swing.JTextField();
        endAtv1 = new javax.swing.JTextField();
        Stat1 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        w = new javax.swing.JTextField();
        bmi = new javax.swing.JTextField();
        h = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        search6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        clist1 = new javax.swing.JTable();
        jButton22 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        CIDv3 = new javax.swing.JTextField();
        search7 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        sn = new javax.swing.JTextField();
        search8 = new javax.swing.JButton();
        cname = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        cnumbe = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        date1 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        camount1 = new javax.swing.JTextField();
        e17 = new javax.swing.JCheckBox();
        e18 = new javax.swing.JCheckBox();
        e19 = new javax.swing.JCheckBox();
        e20 = new javax.swing.JCheckBox();
        e21 = new javax.swing.JCheckBox();
        e22 = new javax.swing.JCheckBox();
        e23 = new javax.swing.JCheckBox();
        e24 = new javax.swing.JCheckBox();
        e25 = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        e26 = new javax.swing.JCheckBox();
        e27 = new javax.swing.JCheckBox();
        e28 = new javax.swing.JCheckBox();
        e29 = new javax.swing.JCheckBox();
        e30 = new javax.swing.JCheckBox();
        e31 = new javax.swing.JCheckBox();
        jLabel50 = new javax.swing.JLabel();
        na8 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        na7 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        na6 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        e32 = new javax.swing.JTextField();
        DELETE = new javax.swing.JButton();
        RESET = new javax.swing.JButton();
        ADD = new javax.swing.JButton();
        UPDATE = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        e33 = new javax.swing.JCheckBox();
        tr = new javax.swing.JLabel();
        log2 = new javax.swing.JTextField();
        jButton24 = new javax.swing.JButton();
        log1 = new javax.swing.JTextField();
        PRINT = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1045, 725));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(244, 744));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Blogout.setBackground(new java.awt.Color(255, 255, 178));
        Blogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EXIT.png"))); // NOI18N
        Blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlogoutActionPerformed(evt);
            }
        });
        jPanel3.add(Blogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 13, 31, 31));

        jButton8.setBackground(new java.awt.Color(255, 255, 178));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 13, 31, 31));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gym icon2.png"))); // NOI18N
        jLabel4.setText("Muscle Factory Fitness Gym");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 253, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 57));

        jPanel1.setBackground(new java.awt.Color(253, 253, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 226));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        memberlist1.setAutoCreateRowSorter(true);
        memberlist1.setBackground(new java.awt.Color(255, 255, 226));
        memberlist1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        memberlist1.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        memberlist1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEM_ID", "FULL NAME", "CONTACT NUMBER", "GENDER", "AGE", "HEIGHT", "WEIGHT", "BMI", "MEM_ACTIVE_AT", "MEM_END_AT", "AMOUNT", "STATUS"
            }
        ));
        memberlist1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        memberlist1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        memberlist1.setGridColor(new java.awt.Color(255, 255, 226));
        memberlist1.setSelectionBackground(new java.awt.Color(255, 255, 226));
        memberlist1.setSelectionForeground(new java.awt.Color(255, 255, 226));
        jScrollPane3.setViewportView(memberlist1);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 45, 730, 480));

        search5.setBackground(new java.awt.Color(255, 255, 204));
        search5.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        search5.setText("Select");
        search5.setBorder(null);
        search5.setBorderPainted(false);
        search5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        search5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search5ActionPerformed(evt);
            }
        });
        jPanel8.add(search5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 90, 30));

        MIDv1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        MIDv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MIDv1MouseClicked(evt);
            }
        });
        jPanel8.add(MIDv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 30));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel11.setText("Member ID");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel23.setBackground(new java.awt.Color(102, 102, 102));
        jLabel23.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel23.setText("Full Name");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        namev1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jPanel8.add(namev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 168, 30));

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel24.setText("Contact Number");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        numberv1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        numberv1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numberv1KeyReleased(evt);
            }
        });
        jPanel8.add(numberv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 168, 30));

        jLabel25.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel25.setText("Gender");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        genderv1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        genderv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel8.add(genderv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 168, 30));

        agev1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jPanel8.add(agev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 168, 30));

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel26.setText("Weight/pound");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, 20));

        jLabel27.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        jLabel27.setText("Membership Monthly");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 144, -1));

        yearv1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        yearv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        yearv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearv1ActionPerformed(evt);
            }
        });
        jPanel8.add(yearv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 60, 20));

        jLabel28.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel28.setText("Registered");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        jLabel29.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel29.setText("Expired At");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));

        jLabel30.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel30.setText("Amount :");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 30));

        amountv1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        amountv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amountv1MouseClicked(evt);
            }
        });
        jPanel8.add(amountv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 90, 30));

        jButton11.setBackground(new java.awt.Color(0, 204, 204));
        jButton11.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add1.jpg"))); // NOI18N
        jButton11.setText("Add    ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 164, -1));

        jButton18.setBackground(new java.awt.Color(255, 51, 51));
        jButton18.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        jButton18.setText("Delete ");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 164, -1));

        jButton19.setBackground(new java.awt.Color(255, 255, 0));
        jButton19.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download.png"))); // NOI18N
        jButton19.setText("Reset ");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 164, -1));

        jButton20.setBackground(new java.awt.Color(0, 153, 255));
        jButton20.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        jButton20.setText("Save Update ");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 164, -1));

        jLabel31.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jLabel31.setText("Month");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, 20));

        jButton21.setBackground(new java.awt.Color(255, 255, 204));
        jButton21.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jButton21.setText("Refresh");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 100, -1));

        Activev1.setFont(new java.awt.Font("MS Gothic", 0, 12)); // NOI18N
        jPanel8.add(Activev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 120, -1));

        endAtv1.setFont(new java.awt.Font("MS Gothic", 0, 12)); // NOI18N
        jPanel8.add(endAtv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 120, -1));

        Stat1.setBackground(new java.awt.Color(255, 255, 204));
        Stat1.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        Stat1.setText("Status ");
        Stat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stat1ActionPerformed(evt);
            }
        });
        jPanel8.add(Stat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 100, -1));

        jButton25.setBackground(new java.awt.Color(255, 255, 204));
        jButton25.setText("Calculate BMI");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel32.setBackground(new java.awt.Color(102, 102, 102));
        jLabel32.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel32.setText("Age");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 30));

        jLabel33.setBackground(new java.awt.Color(102, 102, 102));
        jLabel33.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel33.setText("Height/inches");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, 20));
        jPanel8.add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 70, -1));

        bmi.setEditable(false);
        jPanel8.add(bmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 150, -1));
        jPanel8.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 70, -1));

        jTabbedPane1.addTab("    Member    ", jPanel8);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search6.setBackground(new java.awt.Color(255, 255, 204));
        search6.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        search6.setText("Search");
        search6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search6ActionPerformed(evt);
            }
        });
        jPanel9.add(search6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 11, -1, 30));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        clist1.setBackground(new java.awt.Color(255, 255, 226));
        clist1.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        clist1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRAN_ID", "FULL NAME", "CONTACT NUMBER", "DATE", "TIME", "TRAINER_ID", "SESSION_ID", "SESSION", "EQUIPMENT", "WEIGHT", "SETS", "REPS", "AMOUNT"
            }
        ));
        clist1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane5.setViewportView(clist1);

        jPanel9.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 51, 720, 480));

        jButton22.setBackground(new java.awt.Color(255, 255, 204));
        jButton22.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jButton22.setText("REFRESH");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 100, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel34.setText("If customer has already registered  just sellect the ID");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 20));

        jLabel43.setBackground(new java.awt.Color(0, 0, 0));
        jLabel43.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel43.setText("Customer ID:");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        CIDv3.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jPanel2.add(CIDv3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, 30));

        search7.setBackground(new java.awt.Color(255, 255, 204));
        search7.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        search7.setText("Select");
        search7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search7ActionPerformed(evt);
            }
        });
        jPanel2.add(search7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 80, 30));

        jLabel44.setBackground(new java.awt.Color(0, 0, 0));
        jLabel44.setFont(new java.awt.Font("MS Gothic", 0, 12)); // NOI18N
        jLabel44.setText("Transaction ID:");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        jLabel45.setBackground(new java.awt.Color(102, 102, 102));
        jLabel45.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel45.setText("Full Name");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        sn.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        sn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                snMouseClicked(evt);
            }
        });
        jPanel2.add(sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 70, 30));

        search8.setBackground(new java.awt.Color(255, 255, 204));
        search8.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        search8.setText("Select");
        search8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search8ActionPerformed(evt);
            }
        });
        jPanel2.add(search8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 80, 30));

        cname.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jPanel2.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 154, 30));

        jLabel47.setBackground(new java.awt.Color(102, 102, 102));
        jLabel47.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel47.setText("Contact Number");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        cnumbe.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        cnumbe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnumbeKeyReleased(evt);
            }
        });
        jPanel2.add(cnumbe, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 154, 30));

        jLabel48.setBackground(new java.awt.Color(102, 102, 102));
        jLabel48.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel48.setText("Date");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        date1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        date1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                date1MouseClicked(evt);
            }
        });
        jPanel2.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 154, 30));

        jLabel60.setBackground(new java.awt.Color(102, 102, 102));
        jLabel60.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel60.setText("Trainer");
        jPanel2.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 30));

        t3.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t3KeyReleased(evt);
            }
        });
        jPanel2.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 154, 30));

        jLabel37.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel37.setText("Amount :");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        camount1.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        camount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                camount1MouseClicked(evt);
            }
        });
        jPanel2.add(camount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 154, 30));

        e17.setBackground(new java.awt.Color(204, 204, 204));
        e17.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e17.setText("Training Bench");
        jPanel2.add(e17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, 20));

        e18.setBackground(new java.awt.Color(204, 204, 204));
        e18.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e18.setText("BarBell Set");
        jPanel2.add(e18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, 20));

        e19.setBackground(new java.awt.Color(204, 204, 204));
        e19.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e19.setText("Kettlebell Set");
        jPanel2.add(e19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, -1, 20));

        e20.setBackground(new java.awt.Color(204, 204, 204));
        e20.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e20.setText("Dumbbell Set");
        jPanel2.add(e20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, 20));

        e21.setBackground(new java.awt.Color(204, 204, 204));
        e21.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e21.setText("Fitness Ball");
        jPanel2.add(e21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        e22.setBackground(new java.awt.Color(204, 204, 204));
        e22.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e22.setText("Rowing Machine");
        jPanel2.add(e22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, -1));

        e23.setBackground(new java.awt.Color(204, 204, 204));
        e23.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e23.setText("Stationary Bicycle");
        jPanel2.add(e23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        e24.setBackground(new java.awt.Color(204, 204, 204));
        e24.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e24.setText("Treadmill");
        jPanel2.add(e24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 20));

        e25.setBackground(new java.awt.Color(204, 204, 204));
        e25.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e25.setText("Pull-Up Frame and Bar");
        jPanel2.add(e25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, 20));

        jLabel35.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel35.setText("Equipment");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 20));

        jLabel49.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel49.setText("Session");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 20));

        e26.setBackground(new java.awt.Color(204, 204, 204));
        e26.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e26.setText("Shoulder");
        jPanel2.add(e26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 20));

        e27.setBackground(new java.awt.Color(204, 204, 204));
        e27.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e27.setText("Abs");
        jPanel2.add(e27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 20));

        e28.setBackground(new java.awt.Color(204, 204, 204));
        e28.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e28.setText("Biceps");
        jPanel2.add(e28, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, 20));

        e29.setBackground(new java.awt.Color(204, 204, 204));
        e29.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e29.setText("Triceps");
        jPanel2.add(e29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, 20));

        e30.setBackground(new java.awt.Color(204, 204, 204));
        e30.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e30.setText("Legs");
        jPanel2.add(e30, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        e31.setBackground(new java.awt.Color(204, 204, 204));
        e31.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e31.setText("Back");
        jPanel2.add(e31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        jLabel50.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jLabel50.setText("Reps");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 720, -1, 30));

        na8.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        na8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                na8MouseClicked(evt);
            }
        });
        jPanel2.add(na8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 710, 150, 30));

        jLabel51.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jLabel51.setText("Sets");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, -1, 30));

        na7.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jPanel2.add(na7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 680, 150, 30));

        jLabel52.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jLabel52.setText("Weight/Kg ");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, 30));

        na6.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jPanel2.add(na6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 150, 30));

        jLabel53.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jLabel53.setText("Other Equipment");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, 30));

        e32.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        jPanel2.add(e32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 150, 30));

        DELETE.setBackground(new java.awt.Color(255, 51, 51));
        DELETE.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        DELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        DELETE.setText("Delete");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        jPanel2.add(DELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 800, 130, 30));

        RESET.setBackground(new java.awt.Color(255, 255, 51));
        RESET.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        RESET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download.png"))); // NOI18N
        RESET.setText("Reset");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });
        jPanel2.add(RESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 770, 130, 30));

        ADD.setBackground(new java.awt.Color(0, 204, 51));
        ADD.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        ADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add1.jpg"))); // NOI18N
        ADD.setText("Add  ");
        ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDActionPerformed(evt);
            }
        });
        jPanel2.add(ADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 770, 130, 30));

        UPDATE.setBackground(new java.awt.Color(0, 102, 255));
        UPDATE.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        UPDATE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        UPDATE.setText("Save Update");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        jPanel2.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 800, 130, 30));

        t4.setFont(new java.awt.Font("MS PGothic", 0, 12)); // NOI18N
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t4MouseClicked(evt);
            }
        });
        jPanel2.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 154, 30));

        jLabel61.setBackground(new java.awt.Color(102, 102, 102));
        jLabel61.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel61.setText("Time");
        jPanel2.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 30));

        e33.setBackground(new java.awt.Color(204, 204, 204));
        e33.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        e33.setText("Chest");
        jPanel2.add(e33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 20));

        tr.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.add(tr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 50, 10));

        jScrollPane7.setViewportView(jPanel2);

        jPanel9.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 530));

        log2.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        log2.setText("TRANSACTION_ID");
        log2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                log2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                log2FocusLost(evt);
            }
        });
        jPanel9.add(log2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 109, 30));

        jButton24.setBackground(new java.awt.Color(255, 255, 204));
        jButton24.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jButton24.setText("Search");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 30));

        log1.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        log1.setText("DATE");
        log1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                log1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                log1FocusLost(evt);
            }
        });
        jPanel9.add(log1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 109, 30));

        PRINT.setBackground(new java.awt.Color(255, 255, 204));
        PRINT.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        PRINT.setText("PRINT");
        PRINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINTActionPerformed(evt);
            }
        });
        jPanel9.add(PRINT, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 100, -1));

        jTabbedPane1.addTab("  Daily Log  ", jPanel9);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1040, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 640));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1040, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlogoutActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Select",JOptionPane.YES_NO_OPTION);

        if (a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_BlogoutActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Are you sure you want to close application?","Select",JOptionPane.YES_NO_OPTION);

        if (a==0){
            System.exit(0);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        cname.setText(null);
        cnumbe.setText(null);
        date1.setText(null);
        camount1.setText(null);
        CIDv3.setText(null);
        namev1.setText(null);
        numberv1.setText(null);
        agev1.setText(null);
        Activev1.setText(null);
        endAtv1.setText(null);
        amountv1.setText(null);
        MIDv1.setText(null);
        log1.setText(null);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void search5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search5ActionPerformed

        DELETE.setEnabled(true);
        ADD.setEnabled(true);
        int checkid=0;
        String MEMBER_ID=MIDv1.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from member where MEMBER_ID='"+MEMBER_ID+"'");
            while(rs.next())
            {
                checkid=1;
                MIDv1.setEditable(true);
                namev1.setText(rs.getString(2));
                numberv1.setText(rs.getString(3));
                genderv1.setEditable(false);
                agev1.setText(rs.getString(5));
                h.setText(rs.getString(6));
                w.setText(rs.getString(7));
                bmi.setText(rs.getString(8));
                Activev1.setText(rs.getString(9));
                endAtv1.setText(rs.getString(10));
                amountv1.setText(rs.getString(11));
            }
            if(checkid==0)
            JOptionPane.showMessageDialog(null,"Member ID does not Exist");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search5ActionPerformed

    private void MIDv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MIDv1MouseClicked

        search5.setEnabled(true);
        try
        {
            int ID=1;
            String str1=String.valueOf(ID);
            MIDv1.setText(str1);
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select max(MEMBER_ID) from member");
            while(rs.next())
            {
                ID=rs.getInt(1);
                ID=ID+1;
                String str=String.valueOf(ID);
                MIDv1.setText(str);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_MIDv1MouseClicked

    private void numberv1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberv1KeyReleased
        String CONTACT_NUMBER=numberv1.getText();
        if(CONTACT_NUMBER.matches("^[0-9]*$") && CONTACT_NUMBER.length()==11){
            numberv1.setBackground(Color.white);
        }else{
            numberv1.setBackground(Color.red);
        }
    }//GEN-LAST:event_numberv1KeyReleased

    private void yearv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearv1ActionPerformed

        int num2 = Integer.parseInt((String)yearv1.getSelectedItem());
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date dateobj = new Date();
        Activev1.setText(df.format(dateobj));

        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.MONTH, num2);
        Date expiryDate = cal.getTime();
        endAtv1.setText(df.format(expiryDate));

    }//GEN-LAST:event_yearv1ActionPerformed

    private void amountv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amountv1MouseClicked
        jButton11.setEnabled(true);
    }//GEN-LAST:event_amountv1MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        int checkid=0;
        String MEMBER_ID=MIDv1.getText();
        String NAME=namev1.getText();
        String CONTACT_NUMBER=numberv1.getText();
        String GENDER=(String)genderv1.getSelectedItem();
        String AGE=agev1.getText();
        String HE=h.getText();
        String WE=w.getText();
        String BMI=bmi.getText();
        String MEM_ACTIVE_AT=Activev1.getText();
        String MEM_END_AT=endAtv1.getText();
        String AMOUNT=amountv1.getText();
        String st=" ";

        if(CONTACT_NUMBER.matches("^[0-9]*$") && CONTACT_NUMBER.length()==11){
            checkid=1;
        }else{
            checkid=0;
            JOptionPane.showMessageDialog(null, "Contact  is Incorrect");
        }

        if(checkid==1)
        try
        {
            Connection co=ConnectionProvider.getCon();
            PreparedStatement ps=co.prepareStatement("insert into member values (?,?,?,?,?,?,?,?,?,?,?,?)");

            ps.setString(1, MEMBER_ID);
            ps.setString(2, NAME);
            ps.setString(3, CONTACT_NUMBER);
            ps.setString(4, GENDER);
            ps.setString(5, AGE);
            ps.setString(6, HE);
            ps.setString(7, WE);
            ps.setString(8, BMI);
            ps.setString(9, MEM_ACTIVE_AT);
            ps.setString(10, MEM_END_AT);
            ps.setString(11, AMOUNT);
            ps.setString(12, st);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Add Succesfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to Delete","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            String MEMBER_ID=MIDv1.getText();
            try
            {
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                st.executeUpdate("delete from member where MEMBER_ID='"+MEMBER_ID+"'");

                JOptionPane.showMessageDialog(null,"Successfully Delete");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Select the member ID first before you want to delere");
            }
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        namev1.setText(null);
        numberv1.setText(null);
        agev1.setText(null);
        Activev1.setText(null);
        endAtv1.setText(null);
        amountv1.setText(null);
        h.setText(null);
        w.setText(null);
        bmi.setText(null);
        MIDv1.setText(null);
        jButton11.setEnabled(false);
        jButton18.setEnabled(false);
        search5.setEnabled(false);
        jButton20.setEnabled(false);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        String MEMBER_ID=MIDv1.getText();
        String NAME=namev1.getText();
        String CONTACT_NUMBER=numberv1.getText();
        String GENDER=(String)genderv1.getSelectedItem();
        String AGE=agev1.getText();
        String HE=h.getText();
        String WE=w.getText();
        String BMI=bmi.getText();
        String MEM_ACTIVE_AT=Activev1.getText();
        String MEM_END_AT=endAtv1.getText();
        String AMOUNT=amountv1.getText();

        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement ps=con.prepareStatement("update member set FULL_NAME=?, CONTACT_NUMBER=?, GENDER=?, AGE=?, HEIGHT=?, WEIGHT=?, BMI=?, MEM_ACTIVE_AT=?, MEM_END_AT=?, AMOUNT=? where MEMBER_ID=?");

            ps.setString(1, NAME);
            ps.setString(2, CONTACT_NUMBER);
            ps.setString(3, GENDER);
            ps.setString(4, AGE);
            ps.setString(5, HE);
            ps.setString(6, WE);
            ps.setString(7, BMI);
            ps.setString(8, MEM_ACTIVE_AT);
            ps.setString(9, MEM_END_AT);
            ps.setString(10, AMOUNT);
            ps.setString(11, MEMBER_ID);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Update Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "select the member ID first before you want to update");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        memberlist1.setModel(new DefaultTableModel(null, new String[]{"MEM_ID","FULL NAME","CONTACT NUMBER","GENDER","AGE","HEIGHT","WEIGHT","BMI","MEM_ACTIVE_AT","MEM_END_AT","AMOUNT","STATUS"}));
        DefaultTableModel model=(DefaultTableModel)memberlist1.getModel();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select * from member");
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12)});
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void Stat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stat1ActionPerformed

        int checkid=0;
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date dateobj = new Date();

        if(checkid == 0){
            try
            {
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery("select * from member where MEMBER_ID");
                JOptionPane.showMessageDialog(null, "Status Updated");
                while(rs.next())

                {
                    checkid=1;
                    String id=rs.getString(1);
                    String end=rs.getString(9);
                    String at=rs.getString(10);
                    Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(at);
                    Date date2=new SimpleDateFormat("yyyy-MM-dd").parse(end);

                    try
                    {
                        PreparedStatement ps=con.prepareStatement("update member set STATUS=? where MEMBER_ID=?");
                        for(int s=0; s<checkid;s++){
                            if(dateobj.before(date1) || dateobj.before(date2)){
                                ps.setString(1, "Active");
                            }else{
                                ps.setString(1, "Inactive");
                            }
                            ps.setString(2, id);
                            ps.executeUpdate();
                        }

                    }

                    catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Something Wrong!!!");
                    }
                }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_Stat1ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        double H = Double.parseDouble(h.getText());
        double W = Double.parseDouble(w.getText());
        double result = ((W * 703)/(H * H));
        String b = String.format("%.2f", result);
        bmi.setText(b);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void search6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search6ActionPerformed
        clist1.setModel(new DefaultTableModel(null, new String[]{"TRAN_ID","FULL NAME","CONTACT NUMBER","DATE","TIME","AMOUNT","TRAINER_ID","SESSION_ID","SESSION","EQUIPMENT","WEIGHT","SETS","REPS"}));
        int checkid=0;
        String date=log1.getText();
        try
        {
            DefaultTableModel model=(DefaultTableModel)clist1.getModel();
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from dailylog where DATE='"+date+"'");
            while(rs.next())
            {
                checkid=1;
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13)});
            }
            if(checkid==0)
            JOptionPane.showMessageDialog(null,"date does not Exist");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search6ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        clist1.setModel(new DefaultTableModel(null, new String[]{"TRAN_ID","FULL NAME","CONTACT NUMBER","DATE","TIME","AMOUNT","TRAINER_ID","SESSION_ID","SESSION","EQUIPMENT","WEIGHT","SETS","REPS"}));
        DefaultTableModel mode=(DefaultTableModel)clist1.getModel();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select * from dailylog");
            while(rs.next())
            {
                mode.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12),rs.getString(13)});
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void search7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search7ActionPerformed
        ADD.setEnabled(true);
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date dateobj = new Date();
        String d=(df.format(dateobj));

        Calendar cal = Calendar.getInstance();
        cal.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        t3.setText(sdf.format(cal.getTime()));

        int D=1;
        String str1=String.valueOf(D);
        sn.setText(str1);

        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet r=st.executeQuery("select max(TRAN_ID) from dailylog");

            while(r.next())
            {
                D=r.getInt(1);
                D=D+1;
                String str=String.valueOf(D);
                sn.setText(str);
            }

            String CUSTOMER_ID=CIDv3.getText();
            String q=sn.getText();
            ResultSet rs=st.executeQuery("select * from member where MEMBER_ID='"+CUSTOMER_ID+"'");
            while(rs.next())
            {
                sn.setText(q);
                cname.setText(rs.getString(2));
                cnumbe.setText(rs.getString(3));
                date1.setText(d);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search7ActionPerformed

    private void snMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_snMouseClicked

        search8.setEnabled(true);
        DELETE.setEnabled(true);
        UPDATE.setEnabled(true);
        try
        {
            int D=1;
            String str1=String.valueOf(D);
            sn.setText(str1);
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select max(TRAN_ID) from dailylog");
            while(rs.next())
            {
                D=rs.getInt(1);
                D=D+1;
                String str=String.valueOf(D);
                sn.setText(str);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_snMouseClicked

    private void search8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search8ActionPerformed

        DELETE.setEnabled(true);
        UPDATE.setEnabled(true);
        int checkid=0;
        String CUSTOMER_ID=sn.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from dailylog where TRAN_ID='"+CUSTOMER_ID+"'");
            while(rs.next())
            {
                checkid=1;
                sn.setEditable(true);
                cname.setText(rs.getString(2));
                cnumbe.setText(rs.getString(3));
                date1.setText(rs.getString(4));
                t3.setText(rs.getString(5));
                camount1.setText(rs.getString(6));
                t3.setText(rs.getString(7));
                tr.setText(rs.getString(8));
                e32.setText(rs.getString(10));
                na6.setText(rs.getString(11));
                na7.setText(rs.getString(12));
                na8.setText(rs.getString(13));
            }
            if(checkid==0)
            JOptionPane.showMessageDialog(null,"Member ID does not Exist");
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_search8ActionPerformed

    private void cnumbeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnumbeKeyReleased
        String CONTACT_NUMBER=cnumbe.getText();
        if(CONTACT_NUMBER.matches("^[0-9]*$") && CONTACT_NUMBER.length()==11){
            cnumbe.setBackground(Color.white);
        }else{
            cnumbe.setBackground(Color.red);
        }
    }//GEN-LAST:event_cnumbeKeyReleased

    private void date1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date1MouseClicked
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date dateobj = new Date();
        date1.setText(df.format(dateobj));
    }//GEN-LAST:event_date1MouseClicked

    private void t3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyReleased

        int checkid=0;
        String D=t3.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from trainer where TRAINER_ID='"+D+"'");
            while(rs.next())
            {
                checkid=1;
                t3.setBackground(Color.white);
            }
            if(checkid==0)
            t3.setBackground(Color.red);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_t3KeyReleased

    private void camount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camount1MouseClicked
        ADD.setEnabled(true);
    }//GEN-LAST:event_camount1MouseClicked

    private void na8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_na8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_na8MouseClicked

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to Delete!!!","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            String CUSTOMER_ID=sn.getText();
            try
            {
                Connection con=ConnectionProvider.getCon();
                Statement st=con.createStatement();
                st.executeUpdate("delete from dailylog where TRAN_ID='"+CUSTOMER_ID+"'");

                JOptionPane.showMessageDialog(null,"Successfully Delete");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "select the customer ID first before you want to delete");
            }
        }
    }//GEN-LAST:event_DELETEActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        cname.setText(null);
        cnumbe.setText(null);
        date1.setText(null);
        camount1.setText(null);
        sn.setText(null);
        search8.setEnabled(false);
        DELETE.setEnabled(false);
        UPDATE.setEnabled(false);
        ADD.setEnabled(false);
        na6.setText(null);
        na7.setText(null);
        na8.setText(null);
        t3.setText(null);
        t3.setText(null);
        e32.setText(null);
    }//GEN-LAST:event_RESETActionPerformed

    private void ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDActionPerformed

        try
        {
            int D=1;
            String str1=String.valueOf(D);
            sn.setText(str1);
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select max(SESSION_ID) from dailylog");
            while(rs.next())
            {
                D=rs.getInt(1);
                D=D+1;
                String str=String.valueOf(D);
                tr.setText(str);
                sn.setText(str);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        int checkid=0;
        String D=t3.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from trainer where TRAINER_ID='"+D+"'");
            while(rs.next())
            {
                checkid=1;
            }
            if(checkid==0){
                JOptionPane.showMessageDialog(null, "Trainer not Exist");}
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        String CONTACT_NUMBE=cnumbe.getText();
        if(CONTACT_NUMBE.matches("^[0-9]*$") && CONTACT_NUMBE.length()==11){
        }else{
            checkid=0;
            JOptionPane.showMessageDialog(null, "Contact  is Incorrect");
        }

        String CUSTOMER_ID=sn.getText();
        String NAME=cname.getText();
        String CONTACT_NUMBER=cnumbe.getText();
        String DATE=date1.getText();
        String TIME=t3.getText();
        String AMOUNT=camount1.getText();
        String TRAINER_ID=t3.getText();
        String WEIGHT=na8.getText();
        String SETS=na7.getText();
        String REPS=na6.getText();
        String SESSION_ID=tr.getText();

        String EQUI="",l="";
        String se="",s="";

        if (e17.isSelected()) {
            String a=e17.getText();
            l=a+ ", " + l;
        }
        if (e18.isSelected()) {
            String a=e18.getText();
            l=a+ ", " + l;
        }
        if (e19.isSelected()) {
            String a=e19.getText();
            l=a+ ", " + l;
        }
        if (e20.isSelected()) {
            String a=e20.getText();
            l=a+ ", " + l;
        }
        if (e21.isSelected()) {
            String a=e21.getText();
            l=a+ ", " + l;
        }
        if (e22.isSelected()) {
            String a=e22.getText();
            l=a+ ", " + l;
        }
        if (e23.isSelected()) {
            String a=e23.getText();
            l=a+ ", " + l;
        }
        if (e24.isSelected()) {
            String a=e24.getText();
            l=a+ ", " + l;
        }
        if (e25.isSelected()) {
            String a=e25.getText();
            l=a+ ", " + l;
        }
        EQUI=l;

        if (e26.isSelected()) {
            String a=e26.getText();
            s=a+ ", " + s;
        }
        if (e27.isSelected()) {
            String a=e27.getText();
            s=a+ ", " + s;
        }
        if (e28.isSelected()) {
            String a=e28.getText();
            s=a+ ", " + s;
        }
        if (e29.isSelected()) {
            String a=e29.getText();
            s=a+ ", " + s;
        }
        if (e30.isSelected()) {
            String a=e30.getText();
            s=a+ ", " + s;
        }
        if (e31.isSelected()) {
            String a=e31.getText();
            s=a+ ", " + s;
        }
        if (e33.isSelected()) {
            String a=e33.getText();
            s=a+ ", " + s;
        }
        se=s;

        if(checkid==1)
        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement ps=con.prepareStatement("insert into dailylog values (?,?,?,?,?,?,?,?,?,?,?,?,?)");

            ps.setString(1, CUSTOMER_ID);
            ps.setString(2, NAME);
            ps.setString(3, CONTACT_NUMBER);
            ps.setString(4, DATE);
            ps.setString(5, TIME);
            ps.setString(6, AMOUNT);
            ps.setString(7, TRAINER_ID);
            ps.setString(8, SESSION_ID);
            ps.setString(9, se);
            ps.setString(10, EQUI);
            if(WEIGHT.isEmpty()){
                ps.setNull(11, Types.DOUBLE);}
            else{
                ps.setString(11, WEIGHT);}
            ps.setString(12, SETS);
            ps.setString(13, REPS);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Add Succesfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "fill up the form first");
        }

    }//GEN-LAST:event_ADDActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        String CUSTOMER_ID=sn.getText();
        String NAME=cname.getText();
        String CONTACT_NUMBER=cnumbe.getText();
        String DATE=date1.getText();
        String AMOUNT=camount1.getText();
        String TRAINER_ID=t3.getText();
        String TIME=t3.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            PreparedStatement ps=con.prepareStatement("update dailylog set FULL_NAME=?, CONTACT_NUMBER=?, DATE=?, TIME=?, AMOUNT=?, TRAINER_ID=? where TRAN_ID=?");

            ps.setString(1, NAME);
            ps.setString(2, CONTACT_NUMBER);
            ps.setString(3, DATE);
            ps.setString(4, TIME);
            ps.setString(5, AMOUNT);
            ps.setString(6, TRAINER_ID);
            ps.setString(7, CUSTOMER_ID);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Update Succesfully");
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "select the customer ID first before you want to update");
        }
    }//GEN-LAST:event_UPDATEActionPerformed

    private void t4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t4MouseClicked
        Calendar cal = Calendar.getInstance();
        cal.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        t3.setText(sdf.format(cal.getTime()));
    }//GEN-LAST:event_t4MouseClicked

    private void log2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_log2FocusGained
        if(log1.getText().equals("TRANSACTION_ID")){
            log1.setText("");
            log1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_log2FocusGained

    private void log2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_log2FocusLost
        if(log1.getText().equals("")){
            log1.setText("TRANSACTION_ID");
            log1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_log2FocusLost

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        clist1.setModel(new DefaultTableModel(null, new String[]{"TRAN_ID","FULL NAME","CONTACT NUMBER","DATE","TIME","AMOUNT","TRAINER_ID","SESSION_ID","SESSION","EQUIPMENT","WEIGHT","SETS","REPS"}));
        DefaultTableModel mode=(DefaultTableModel)clist1.getModel();
        String Id=log2.getText();
        try
        {
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select * from dailylog where DATE='"+Id+"'");
            while(rs.next())
            {
                mode.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(13),rs.getString(13)});
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void log1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_log1FocusGained
        if(log1.getText().equals("DATE")){
            log1.setText("");
            log1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_log1FocusGained

    private void log1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_log1FocusLost
        if(log1.getText().equals("")){
            log1.setText("DATE");
            log1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_log1FocusLost

    private void PRINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINTActionPerformed

        try{

            Connection con=ConnectionProvider.getCon();
            JasperDesign jasdi= JRXmlLoader.load("C:\\Users\\User\\Documents\\NetBeansProjects\\Gym management System\\src\\reportDailylog.jrxml");
            String sql="select * from dailylog";
            JRDesignQuery newQuery=new JRDesignQuery();
            newQuery.setText(sql);
            jasdi.setQuery(newQuery);
            JasperReport js=JasperCompileManager.compileReport(jasdi);
            JasperPrint jp=JasperFillManager.fillReport(js,null,con);
            JasperViewer.viewReport(jp);
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_PRINTActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new monitoring().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD;
    private javax.swing.JTextField Activev1;
    private javax.swing.JButton Blogout;
    private javax.swing.JTextField CIDv3;
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField MIDv1;
    private javax.swing.JButton PRINT;
    private javax.swing.JButton RESET;
    private javax.swing.JButton Stat1;
    private javax.swing.JButton UPDATE;
    private javax.swing.JTextField agev1;
    private javax.swing.JTextField amountv1;
    private javax.swing.JTextField bmi;
    private javax.swing.JTextField camount1;
    private javax.swing.JTable clist1;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cnumbe;
    private javax.swing.JTextField date1;
    private javax.swing.JCheckBox e17;
    private javax.swing.JCheckBox e18;
    private javax.swing.JCheckBox e19;
    private javax.swing.JCheckBox e20;
    private javax.swing.JCheckBox e21;
    private javax.swing.JCheckBox e22;
    private javax.swing.JCheckBox e23;
    private javax.swing.JCheckBox e24;
    private javax.swing.JCheckBox e25;
    private javax.swing.JCheckBox e26;
    private javax.swing.JCheckBox e27;
    private javax.swing.JCheckBox e28;
    private javax.swing.JCheckBox e29;
    private javax.swing.JCheckBox e30;
    private javax.swing.JCheckBox e31;
    private javax.swing.JTextField e32;
    private javax.swing.JCheckBox e33;
    private javax.swing.JTextField endAtv1;
    private javax.swing.JComboBox<String> genderv1;
    private javax.swing.JTextField h;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField log1;
    private javax.swing.JTextField log2;
    private javax.swing.JTable memberlist1;
    private javax.swing.JTextField na6;
    private javax.swing.JTextField na7;
    private javax.swing.JTextField na8;
    private javax.swing.JTextField namev1;
    private javax.swing.JTextField numberv1;
    private javax.swing.JButton search5;
    private javax.swing.JButton search6;
    private javax.swing.JButton search7;
    private javax.swing.JButton search8;
    private javax.swing.JTextField sn;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JLabel tr;
    private javax.swing.JTextField w;
    private javax.swing.JComboBox<String> yearv1;
    // End of variables declaration//GEN-END:variables
}
